M48
; DRILL file {KiCad 9.0.7} date 2026-02-01T23:58:05+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-01T23:58:05+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.889
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.300
%
G90
G05
T1
X118.75Y-101.144
X118.75Y-105.544
T2
X181.25Y-104.944
X181.25Y-109.744
M30
